# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"3\n\x11ImageReferenceMsg\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\"&\n\x13SessionReferenceMsg\x12\x0f\n\x07session\x18\x01 \x01(\t\"4\n\x11SessionDetailsMsg\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x0e\n\x06images\x18\x02 \x01(\x05\"\xa9\x01\n\x16ImageSequenceHeaderMsg\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x05\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x03\x12\x0f\n\x07updated\x18\x04 \x01(\x03\x12\r\n\x05score\x18\x05 \x01(\x02\x12\r\n\x05\x63lazz\x18\x06 \x01(\x05\x12\r\n\x05width\x18\x07 \x01(\x05\x12\x0e\n\x06height\x18\x08 \x01(\x05\x12\x10\n\x08segments\x18\t \x01(\x05\"8\n\x17ImageSequenceSegmentMsg\x12\x0f\n\x07segment\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREFERENCEMSG._serialized_start=18
  _IMAGEREFERENCEMSG._serialized_end=69
  _SESSIONREFERENCEMSG._serialized_start=71
  _SESSIONREFERENCEMSG._serialized_end=109
  _SESSIONDETAILSMSG._serialized_start=111
  _SESSIONDETAILSMSG._serialized_end=163
  _IMAGESEQUENCEHEADERMSG._serialized_start=166
  _IMAGESEQUENCEHEADERMSG._serialized_end=335
  _IMAGESEQUENCESEGMENTMSG._serialized_start=337
  _IMAGESEQUENCESEGMENTMSG._serialized_end=393
# @@protoc_insertion_point(module_scope)
