# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tipc.proto\x12\x07session\"\xf4\x02\n\nSessionMsg\x12-\n\x0bnew_session\x18\x01 \x01(\x0b\x32\x16.session.NewSessionMsgH\x00\x12\x31\n\rnew_detection\x18\x02 \x01(\x0b\x32\x18.session.NewDetectionMsgH\x00\x12@\n\x15update_detection_meta\x18\x03 \x01(\x0b\x32\x1f.session.UpdateDetectionMetaMsgH\x00\x12\x37\n\x10update_detection\x18\x04 \x01(\x0b\x32\x1b.session.UpdateDetectionMsgH\x00\x12)\n\x0cstream_frame\x18\x05 \x01(\x0b\x32\x11.session.FrameMsgH\x00\x12&\n\x07storage\x18\x06 \x01(\x0b\x32\x13.session.StorageMsgH\x00\x12-\n\x0b\x61\x63tive_flow\x18\x07 \x01(\x0b\x32\x16.session.ActiveFlowMsgH\x00\x42\x07\n\x05inner\" \n\rNewSessionMsg\x12\x0f\n\x07session\x18\x01 \x01(\t\"\x84\x01\n\x0fNewDetectionMsg\x12\x11\n\tdetection\x18\x01 \x01(\x05\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x03\x12\r\n\x05score\x18\x03 \x01(\x02\x12\r\n\x05\x63lazz\x18\x04 \x01(\x05\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\x12\x10\n\x08img_data\x18\x07 \x01(\x0c\"<\n\x16UpdateDetectionMetaMsg\x12\x11\n\tdetection\x18\x01 \x01(\x05\x12\x0f\n\x07updated\x18\x02 \x01(\x03\"x\n\x12UpdateDetectionMsg\x12\x11\n\tdetection\x18\x01 \x01(\x05\x12\x0f\n\x07updated\x18\x02 \x01(\x03\x12\r\n\x05score\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x10\n\x08img_data\x18\x06 \x01(\x0c\",\n\x08\x46rameMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\"\x1d\n\nStorageMsg\x12\x0f\n\x07mounted\x18\x01 \x01(\x08\"\x1d\n\rActiveFlowMsg\x12\x0c\n\x04\x66low\x18\x01 \x01(\x05\"D\n\nControlMsg\x12-\n\x08set_flow\x18\x01 \x01(\x0b\x32\x19.session.SetActiveFlowMsgH\x00\x42\x07\n\x05inner\" \n\x10SetActiveFlowMsg\x12\x0c\n\x04\x66low\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONMSG._serialized_start=23
  _SESSIONMSG._serialized_end=395
  _NEWSESSIONMSG._serialized_start=397
  _NEWSESSIONMSG._serialized_end=429
  _NEWDETECTIONMSG._serialized_start=432
  _NEWDETECTIONMSG._serialized_end=564
  _UPDATEDETECTIONMETAMSG._serialized_start=566
  _UPDATEDETECTIONMETAMSG._serialized_end=626
  _UPDATEDETECTIONMSG._serialized_start=628
  _UPDATEDETECTIONMSG._serialized_end=748
  _FRAMEMSG._serialized_start=750
  _FRAMEMSG._serialized_end=794
  _STORAGEMSG._serialized_start=796
  _STORAGEMSG._serialized_end=825
  _ACTIVEFLOWMSG._serialized_start=827
  _ACTIVEFLOWMSG._serialized_end=856
  _CONTROLMSG._serialized_start=858
  _CONTROLMSG._serialized_end=926
  _SETACTIVEFLOWMSG._serialized_start=928
  _SETACTIVEFLOWMSG._serialized_end=960
# @@protoc_insertion_point(module_scope)
